version: '3.8'

services:
  db_postgres:
    image: postgres:14.2-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
  server:
    build: .
    depends_on:
      - db_postgres
    ports:
      - 5000:5000
